# Nacos 配置文件名
NACOS_CONFIG_URL: 127.0.0.1:8848
NACOS_CONFIG_USERNAME: nacos
NACOS_CONFIG_PASSWORD: nacos
NACOS_CONFIG_GROUP: DEFAULT_GROUP
NACOS_SWITCH_CONFIG: switch-config.yaml
NACOS_WEB_CONFIG: web-config.yaml