# Port 配置
SERVER_PORT: 8060

# Path 配置
CONTEXT_PATH: /api/training

# Nacos 配置文件名
NACOS_CONFIG_URL: 120.26.120.98:8848
NACOS_CONFIG_USERNAME: nacos
NACOS_CONFIG_PASSWORD: nacos
NACOS_CONFIG_GROUP: DEFAULT_GROUP
NACOS_SWITCH_CONFIG: switch-config.yaml
NACOS_WEB_CONFIG: web-config.yaml

# MySQL 配置
MYSQL_HOST: 120.26.120.98
MYSQL_PORT: 3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: 123456
MYSQL_DATABASE: hoj

# Redis 配置
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: 123456