spring:
  application:
    name: oj-passport

  # 默认 dev 环境
  profiles:
    active: dev

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # Redis 配置
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
      timeout: 5000
      password: 123456
      connect-timeout: 100000

  # 注册到 Nacos 服务
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

server:
  address: 0.0.0.0
  port: 8000
  servlet:
    session:
      cookie:
        max-age: 2592000
        path: /api

# MybatisPlus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    banner: false
