server:
  port: 7999

spring:
  profiles:
    include: route
  application:
    name: oj-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848


springdoc:
  default-flat-param-object: true
# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      enabled: true
      # OpenAPI 3.0 规范
      version: openapi3
      excluded-services:
        - oj-gateway