spring:
  cloud:
    gateway:
      routes:
        - id: oj-passport
          uri: lb://oj-passport
          predicates:
            - Path=/api/passport/**
      discovery:
        locator:
          enabled: true