spring:
  cloud:
    gateway:
      routes:
        - id: oj-passport
          uri: lb://oj-passport
          predicates:
            - Path=/api/passport/**
        - id: oj-account
          uri: lb://oj-account
          predicates:
            - Path=/api/account/**
        - id: oj-judge
          uri: lb://oj-judge
          predicates:
            - Path=/api/judge/**
        - id: oj-judgeserve
          uri: lb://oj-judgeserve
          predicates:
            - Path=/api/judgeserve/**
        - id: oj-problem
          uri: lb://oj-problem
          predicates:
            - Path=/api/problem/**
        - id: oj-common
          uri: lb://oj-common
          predicates:
            - Path=/api/common/**
        - id: oj-training
          uri: lb://oj-training
          predicates:
            - Path=/api/training/**
        - id: oj-file
          uri: lb://oj-file
          predicates:
            - Path=/api/file/**
        - id: oj-admin
          uri: lb://oj-admin
          predicates:
            - Path=/api/admin/**

        # 添加以下API文档路由
        - id: oj-passport-docs
          uri: lb://oj-passport
          predicates:
            - Path=/api/passport/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-account-docs
          uri: lb://oj-account
          predicates:
            - Path=/api/account/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-judge-docs
          uri: lb://oj-judge
          predicates:
            - Path=/api/judge/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-judgeserve-docs
          uri: lb://oj-judgeserve
          predicates:
            - Path=/api/judgeserve/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-problem-docs
          uri: lb://oj-problem
          predicates:
            - Path=/api/problem/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-common-docs
          uri: lb://oj-common
          predicates:
            - Path=/api/common/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-training-docs
          uri: lb://oj-training
          predicates:
            - Path=/api/training/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-file-docs
          uri: lb://oj-file
          predicates:
            - Path=/api/file/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: oj-admin-docs
          uri: lb://oj-admin
          predicates:
            - Path=/api/admin/v3/api-docs/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true